-- Synthetic DB2 extraction catalog for portfolio demonstration.
-- Library and object names are generated, not internal Venetian identifiers.
SET CURRENT DEGREE = 'ANY';

-- HOSPITALITY.RESERVATION: bounded watermark extract
SELECT
    RESERVATION_ID AS SOURCE_BUSINESS_KEY,
    GUEST_ID,
    PROPERTY_CODE,
    ARRIVAL_DATE,
    DEPARTURE_DATE,
    STATUS_CD,
    ROOM_TYPE_CD,
    ROOM_QTY,
    REVENUE_AMT,
    UPDATED_TS,
    UPDATED_SCN AS SOURCE_WATERMARK
FROM HOSPITALITY.RESERVATION
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
WITH UR;

SELECT COALESCE(MAX(UPDATED_SCN),0) AS HIGH_WATERMARK
FROM HOSPITALITY.RESERVATION
WITH UR;

SELECT RESERVATION_ID,COUNT(*) AS DUP_COUNT
FROM HOSPITALITY.RESERVATION
GROUP BY RESERVATION_ID
HAVING COUNT(*) > 1
WITH UR;

-- GAMING.SLOT_ACTIVITY: bounded watermark extract
SELECT
    EVENT_ID AS SOURCE_BUSINESS_KEY,
    MACHINE_ID,
    PROPERTY_CODE,
    EVENT_TS,
    EVENT_TYPE_CD,
    COIN_IN_AMT,
    PAYOUT_AMT,
    JACKPOT_AMT,
    SCHEMA_VERSION,
    EVENT_SCN AS SOURCE_WATERMARK
FROM GAMING.SLOT_ACTIVITY
WHERE EVENT_SCN > CAST(? AS BIGINT)
  AND EVENT_SCN <= CAST(? AS BIGINT)
WITH UR;

SELECT COALESCE(MAX(EVENT_SCN),0) AS HIGH_WATERMARK
FROM GAMING.SLOT_ACTIVITY
WITH UR;

SELECT EVENT_ID,COUNT(*) AS DUP_COUNT
FROM GAMING.SLOT_ACTIVITY
GROUP BY EVENT_ID
HAVING COUNT(*) > 1
WITH UR;

-- LOYALTY.REWARD_ACTIVITY: bounded watermark extract
SELECT
    REWARD_EVENT_ID AS SOURCE_BUSINESS_KEY,
    GUEST_ID,
    PROPERTY_CODE,
    EVENT_TS,
    ACTIVITY_TYPE_CD,
    POINTS_QTY,
    VALUE_AMT,
    TIER_CD,
    EVENT_SCN AS SOURCE_WATERMARK
FROM LOYALTY.REWARD_ACTIVITY
WHERE EVENT_SCN > CAST(? AS BIGINT)
  AND EVENT_SCN <= CAST(? AS BIGINT)
WITH UR;

SELECT COALESCE(MAX(EVENT_SCN),0) AS HIGH_WATERMARK
FROM LOYALTY.REWARD_ACTIVITY
WITH UR;

SELECT REWARD_EVENT_ID,COUNT(*) AS DUP_COUNT
FROM LOYALTY.REWARD_ACTIVITY
GROUP BY REWARD_EVENT_ID
HAVING COUNT(*) > 1
WITH UR;

-- FINANCE.PAYMENT_TRANSACTION: bounded watermark extract
SELECT
    TRANSACTION_ID AS SOURCE_BUSINESS_KEY,
    PROPERTY_CODE,
    BUSINESS_TS,
    PAYMENT_TYPE_CD,
    AMOUNT,
    CURRENCY_CD,
    STATUS_CD,
    UPDATED_SCN AS SOURCE_WATERMARK
FROM FINANCE.PAYMENT_TRANSACTION
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
WITH UR;

SELECT COALESCE(MAX(UPDATED_SCN),0) AS HIGH_WATERMARK
FROM FINANCE.PAYMENT_TRANSACTION
WITH UR;

SELECT TRANSACTION_ID,COUNT(*) AS DUP_COUNT
FROM FINANCE.PAYMENT_TRANSACTION
GROUP BY TRANSACTION_ID
HAVING COUNT(*) > 1
WITH UR;

-- PROPERTY_OPS.WORK_ORDER: bounded watermark extract
SELECT
    WORK_ORDER_ID AS SOURCE_BUSINESS_KEY,
    PROPERTY_CODE,
    ZONE_CODE,
    OPEN_TS,
    CLOSE_TS,
    PRIORITY_CD,
    STATUS_CD,
    CATEGORY_CD,
    UPDATED_SCN AS SOURCE_WATERMARK
FROM PROPERTY_OPS.WORK_ORDER
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
WITH UR;

SELECT COALESCE(MAX(UPDATED_SCN),0) AS HIGH_WATERMARK
FROM PROPERTY_OPS.WORK_ORDER
WITH UR;

SELECT WORK_ORDER_ID,COUNT(*) AS DUP_COUNT
FROM PROPERTY_OPS.WORK_ORDER
GROUP BY WORK_ORDER_ID
HAVING COUNT(*) > 1
WITH UR;

-- Reservation + generated guest profile canonical source projection
SELECT
    R.RESERVATION_ID,
    R.GUEST_ID,
    G.LOYALTY_ID,
    G.LOYALTY_TIER_CD,
    R.PROPERTY_CODE,
    R.ARRIVAL_DATE,
    R.DEPARTURE_DATE,
    R.STATUS_CD,
    R.ROOM_TYPE_CD,
    R.ROOM_QTY,
    R.REVENUE_AMT,
    R.UPDATED_SCN,
    R.UPDATED_TS
FROM HOSPITALITY.RESERVATION R
LEFT JOIN HOSPITALITY.GUEST_PROFILE G
  ON G.GUEST_ID=R.GUEST_ID
WHERE R.UPDATED_SCN > CAST(? AS BIGINT)
  AND R.UPDATED_SCN <= CAST(? AS BIGINT)
WITH UR;

-- Gaming event sequence integrity by property
SELECT
    PROPERTY_CODE,
    MIN(EVENT_SCN) AS MIN_SCN,
    MAX(EVENT_SCN) AS MAX_SCN,
    COUNT(*) AS ROW_COUNT,
    MAX(EVENT_SCN)-MIN(EVENT_SCN)+1-COUNT(*) AS SEQUENCE_GAP_ESTIMATE
FROM GAMING.SLOT_ACTIVITY
WHERE EVENT_SCN > CAST(? AS BIGINT)
  AND EVENT_SCN <= CAST(? AS BIGINT)
GROUP BY PROPERTY_CODE
WITH UR;

-- Reservation source profiling
SELECT
    PROPERTY_CODE,
    STATUS_CD,
    COUNT(*) AS ROW_COUNT,
    SUM(ROOM_QTY) AS ROOM_QTY,
    SUM(REVENUE_AMT) AS REVENUE_AMT,
    MIN(ARRIVAL_DATE) AS MIN_ARRIVAL_DATE,
    MAX(DEPARTURE_DATE) AS MAX_DEPARTURE_DATE
FROM HOSPITALITY.RESERVATION
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
GROUP BY PROPERTY_CODE,STATUS_CD
WITH UR;

-- Reward source profiling
SELECT
    PROPERTY_CODE,
    ACTIVITY_TYPE_CD,
    COUNT(*) AS ROW_COUNT,
    SUM(POINTS_QTY) AS POINTS_QTY,
    SUM(VALUE_AMT) AS VALUE_AMT
FROM LOYALTY.REWARD_ACTIVITY
WHERE EVENT_SCN > CAST(? AS BIGINT)
  AND EVENT_SCN <= CAST(? AS BIGINT)
GROUP BY PROPERTY_CODE,ACTIVITY_TYPE_CD
WITH UR;

-- Payment source profiling
SELECT
    PROPERTY_CODE,
    PAYMENT_TYPE_CD,
    CURRENCY_CD,
    STATUS_CD,
    COUNT(*) AS ROW_COUNT,
    SUM(AMOUNT) AS AMOUNT
FROM FINANCE.PAYMENT_TRANSACTION
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
GROUP BY PROPERTY_CODE,PAYMENT_TYPE_CD,CURRENCY_CD,STATUS_CD
WITH UR;

-- Operational source profiling
SELECT
    PROPERTY_CODE,
    ZONE_CODE,
    PRIORITY_CD,
    STATUS_CD,
    COUNT(*) AS ROW_COUNT,
    MIN(OPEN_TS) AS OLDEST_OPEN_TS,
    MAX(CLOSE_TS) AS LATEST_CLOSE_TS
FROM PROPERTY_OPS.WORK_ORDER
WHERE UPDATED_SCN > CAST(? AS BIGINT)
  AND UPDATED_SCN <= CAST(? AS BIGINT)
GROUP BY PROPERTY_CODE,ZONE_CODE,PRIORITY_CD,STATUS_CD
WITH UR;

-- Null-key diagnostics
SELECT 'RESERVATION' AS ENTITY,COUNT(*) AS INVALID_COUNT
FROM HOSPITALITY.RESERVATION
WHERE RESERVATION_ID IS NULL OR PROPERTY_CODE IS NULL
WITH UR;

SELECT 'SLOT_ACTIVITY' AS ENTITY,COUNT(*) AS INVALID_COUNT
FROM GAMING.SLOT_ACTIVITY
WHERE EVENT_ID IS NULL OR MACHINE_ID IS NULL OR PROPERTY_CODE IS NULL
WITH UR;

SELECT 'REWARD_ACTIVITY' AS ENTITY,COUNT(*) AS INVALID_COUNT
FROM LOYALTY.REWARD_ACTIVITY
WHERE REWARD_EVENT_ID IS NULL OR GUEST_ID IS NULL OR PROPERTY_CODE IS NULL
WITH UR;

SELECT 'PAYMENT_TRANSACTION' AS ENTITY,COUNT(*) AS INVALID_COUNT
FROM FINANCE.PAYMENT_TRANSACTION
WHERE TRANSACTION_ID IS NULL OR PROPERTY_CODE IS NULL
WITH UR;

SELECT 'WORK_ORDER' AS ENTITY,COUNT(*) AS INVALID_COUNT
FROM PROPERTY_OPS.WORK_ORDER
WHERE WORK_ORDER_ID IS NULL OR PROPERTY_CODE IS NULL
WITH UR;

-- Date/time diagnostics
SELECT COUNT(*) AS INVALID_STAY_COUNT
FROM HOSPITALITY.RESERVATION
WHERE DEPARTURE_DATE < ARRIVAL_DATE
WITH UR;

SELECT COUNT(*) AS FUTURE_EVENT_COUNT
FROM GAMING.SLOT_ACTIVITY
WHERE EVENT_TS > CURRENT TIMESTAMP + 5 MINUTES
WITH UR;

SELECT COUNT(*) AS NEGATIVE_PAYMENT_COUNT
FROM FINANCE.PAYMENT_TRANSACTION
WHERE AMOUNT < 0
  AND PAYMENT_TYPE_CD NOT IN ('REFUND','REVERSAL')
WITH UR;

-- Property distribution checks
SELECT PROPERTY_CODE,COUNT(*) AS RESERVATION_ROWS
FROM HOSPITALITY.RESERVATION
GROUP BY PROPERTY_CODE
ORDER BY RESERVATION_ROWS DESC
WITH UR;

SELECT PROPERTY_CODE,COUNT(*) AS GAMING_ROWS
FROM GAMING.SLOT_ACTIVITY
GROUP BY PROPERTY_CODE
ORDER BY GAMING_ROWS DESC
WITH UR;

SELECT PROPERTY_CODE,COUNT(*) AS REWARD_ROWS
FROM LOYALTY.REWARD_ACTIVITY
GROUP BY PROPERTY_CODE
ORDER BY REWARD_ROWS DESC
WITH UR;

-- Recent-window diagnostics for operational runbooks
SELECT COUNT(*) AS RESERVATION_UPDATES_LAST_HOUR
FROM HOSPITALITY.RESERVATION
WHERE UPDATED_TS >= CURRENT TIMESTAMP - 1 HOUR
WITH UR;

SELECT COUNT(*) AS GAMING_EVENTS_LAST_5_MIN
FROM GAMING.SLOT_ACTIVITY
WHERE EVENT_TS >= CURRENT TIMESTAMP - 5 MINUTES
WITH UR;

SELECT COUNT(*) AS REWARD_EVENTS_LAST_15_MIN
FROM LOYALTY.REWARD_ACTIVITY
WHERE EVENT_TS >= CURRENT TIMESTAMP - 15 MINUTES
WITH UR;

SELECT COUNT(*) AS PAYMENT_EVENTS_LAST_5_MIN
FROM FINANCE.PAYMENT_TRANSACTION
WHERE BUSINESS_TS >= CURRENT TIMESTAMP - 5 MINUTES
WITH UR;

SELECT COUNT(*) AS OPEN_CRITICAL_WORK_ORDERS
FROM PROPERTY_OPS.WORK_ORDER
WHERE PRIORITY_CD='CRITICAL'
  AND STATUS_CD NOT IN ('CLOSED','CANCELLED')
WITH UR;
