version: 2
models:
  - name: fct_hotel_occupancy_daily
    columns:
      - name: property_code
        tests: [not_null]
      - name: stay_date
        tests: [not_null]
  - name: fct_gaming_performance_5min
    columns:
      - name: property_code
        tests: [not_null]
      - name: window_start
        tests: [not_null]
  - name: mart_guest_360
    columns:
      - name: enterprise_guest_id
        tests: [not_null, unique]
  - name: mart_executive_property_daily
    columns:
      - name: business_date
        tests: [not_null]
      - name: property_code
        tests: [not_null]
