-- DB2 generated source pattern: gaming activity incremental extract.
SELECT
    EVENT_ID,
    SESSION_ID,
    PROPERTY_CODE,
    DEVICE_TOKEN,
    GUEST_TOKEN,
    GAME_CODE,
    EVENT_TYPE,
    EVENT_TS,
    DECIMAL(COIN_IN, 19, 2) AS COIN_IN,
    DECIMAL(PAYOUT, 19, 2) AS PAYOUT,
    DECIMAL(JACKPOT_AMOUNT, 19, 2) AS JACKPOT_AMOUNT,
    SOURCE_SEQUENCE
FROM GAMING.ACTIVITY_EVENT
WHERE SOURCE_SEQUENCE > :low_watermark
  AND SOURCE_SEQUENCE <= :high_watermark
  AND EVENT_TS <= CURRENT TIMESTAMP + 5 MINUTES
ORDER BY SOURCE_SEQUENCE
WITH UR;
