SELECT
    REWARD_EVENT_ID,
    GUEST_TOKEN,
    PROPERTY_CODE,
    ACTIVITY_TS,
    ACTIVITY_TYPE,
    SOURCE_DOMAIN,
    POINTS_DELTA,
    DECIMAL(MONETARY_VALUE, 19, 2) AS MONETARY_VALUE,
    SOURCE_SEQUENCE
FROM LOYALTY.REWARD_ACTIVITY
WHERE SOURCE_SEQUENCE > :low_watermark
  AND SOURCE_SEQUENCE <= :high_watermark
ORDER BY SOURCE_SEQUENCE
WITH UR;
